// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0
// source: category.sql

package db

import (
	"context"
)

const readCategory = `-- name: ReadCategory :many
SELECT category_id, category_name, created_on, image_url, status
FROM public.categories
`

func (q *Queries) ReadCategory(ctx context.Context) ([]Category, error) {
	rows, err := q.db.QueryContext(ctx, readCategory)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Category
	for rows.Next() {
		var i Category
		if err := rows.Scan(
			&i.CategoryID,
			&i.CategoryName,
			&i.CreatedOn,
			&i.ImageUrl,
			&i.Status,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
