// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package db

import (
	"database/sql"
	"database/sql/driver"
	"fmt"
)

type EnumAccess string

const (
	EnumAccessUser  EnumAccess = "user"
	EnumAccessAdmin EnumAccess = "admin"
)

func (e *EnumAccess) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = EnumAccess(s)
	case string:
		*e = EnumAccess(s)
	default:
		return fmt.Errorf("unsupported scan type for EnumAccess: %T", src)
	}
	return nil
}

type NullEnumAccess struct {
	EnumAccess EnumAccess `json:"enum_access"`
	Valid      bool       `json:"valid"` // Valid is true if EnumAccess is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullEnumAccess) Scan(value interface{}) error {
	if value == nil {
		ns.EnumAccess, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.EnumAccess.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullEnumAccess) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.EnumAccess), nil
}

type EnumGender string

const (
	EnumGenderMale      EnumGender = "male"
	EnumGenderFemale    EnumGender = "female"
	EnumGenderUndefined EnumGender = "undefined"
)

func (e *EnumGender) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = EnumGender(s)
	case string:
		*e = EnumGender(s)
	default:
		return fmt.Errorf("unsupported scan type for EnumGender: %T", src)
	}
	return nil
}

type NullEnumGender struct {
	EnumGender EnumGender `json:"enum_gender"`
	Valid      bool       `json:"valid"` // Valid is true if EnumGender is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullEnumGender) Scan(value interface{}) error {
	if value == nil {
		ns.EnumGender, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.EnumGender.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullEnumGender) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.EnumGender), nil
}

type EnumOrderStatus string

const (
	EnumOrderStatusProcessing     EnumOrderStatus = "processing"
	EnumOrderStatusConfirmed      EnumOrderStatus = "confirmed"
	EnumOrderStatusDelivered      EnumOrderStatus = "delivered"
	EnumOrderStatusCancelled      EnumOrderStatus = "cancelled"
	EnumOrderStatusPendingPayment EnumOrderStatus = "pending-payment"
	EnumOrderStatusRefunded       EnumOrderStatus = "refunded"
)

func (e *EnumOrderStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = EnumOrderStatus(s)
	case string:
		*e = EnumOrderStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for EnumOrderStatus: %T", src)
	}
	return nil
}

type NullEnumOrderStatus struct {
	EnumOrderStatus EnumOrderStatus `json:"enum_order_status"`
	Valid           bool            `json:"valid"` // Valid is true if EnumOrderStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullEnumOrderStatus) Scan(value interface{}) error {
	if value == nil {
		ns.EnumOrderStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.EnumOrderStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullEnumOrderStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.EnumOrderStatus), nil
}

type EnumStatus string

const (
	EnumStatusActive   EnumStatus = "active"
	EnumStatusInactive EnumStatus = "inactive"
)

func (e *EnumStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = EnumStatus(s)
	case string:
		*e = EnumStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for EnumStatus: %T", src)
	}
	return nil
}

type NullEnumStatus struct {
	EnumStatus EnumStatus `json:"enum_status"`
	Valid      bool       `json:"valid"` // Valid is true if EnumStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullEnumStatus) Scan(value interface{}) error {
	if value == nil {
		ns.EnumStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.EnumStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullEnumStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.EnumStatus), nil
}

type EnumType string

const (
	EnumTypeVoucher EnumType = "voucher"
	EnumTypeCoupon  EnumType = "coupon"
)

func (e *EnumType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = EnumType(s)
	case string:
		*e = EnumType(s)
	default:
		return fmt.Errorf("unsupported scan type for EnumType: %T", src)
	}
	return nil
}

type NullEnumType struct {
	EnumType EnumType `json:"enum_type"`
	Valid    bool     `json:"valid"` // Valid is true if EnumType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullEnumType) Scan(value interface{}) error {
	if value == nil {
		ns.EnumType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.EnumType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullEnumType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.EnumType), nil
}

type Cart struct {
	CartID       int32          `json:"cart_id"`
	UserID       sql.NullInt32  `json:"user_id"`
	DiscountCode sql.NullString `json:"discount_code"`
	CreatedOn    sql.NullTime   `json:"created_on"`
	UpdatedOn    sql.NullTime   `json:"updated_on"`
}

type CartDetail struct {
	CdID          int32         `json:"cd_id"`
	CartID        sql.NullInt32 `json:"cart_id"`
	ProductID     sql.NullInt32 `json:"product_id"`
	ProductPrice  sql.NullInt32 `json:"product_price"`
	Quantity      sql.NullInt32 `json:"quantity"`
	DeliveryPrice sql.NullInt32 `json:"delivery_price"`
}

type Category struct {
	CategoryID   int32          `json:"category_id"`
	CategoryName string         `json:"category_name"`
	CreatedOn    sql.NullTime   `json:"created_on"`
	ImageUrl     sql.NullString `json:"image_url"`
	Status       NullEnumStatus `json:"status"`
}

type Country struct {
	CountryID      int32  `json:"country_id"`
	CountryName    string `json:"country_name"`
	Currency       string `json:"currency"`
	CurrencySymbol string `json:"currency_symbol"`
}

type Discount struct {
	DiscountID int32          `json:"discount_id"`
	Code       string         `json:"code"`
	Status     NullEnumStatus `json:"status"`
	Type       NullEnumType   `json:"type"`
	Value      sql.NullInt32  `json:"value"`
	CreatedOn  sql.NullTime   `json:"created_on"`
	UpdatedOn  sql.NullTime   `json:"updated_on"`
	CreatedBy  sql.NullInt32  `json:"created_by"`
	UpdatedBy  sql.NullInt32  `json:"updated_by"`
	ExpiredOn  sql.NullTime   `json:"expired_on"`
}

type Order struct {
	OrderID              string              `json:"order_id"`
	UserID               sql.NullInt32       `json:"user_id"`
	Price                sql.NullInt32       `json:"price"`
	DeliveryPrice        sql.NullInt32       `json:"delivery_price"`
	Total                sql.NullInt32       `json:"total"`
	Status               NullEnumOrderStatus `json:"status"`
	CreatedOn            sql.NullTime        `json:"created_on"`
	BillingFirstName     string              `json:"billing_first_name"`
	BillingLastName      string              `json:"billing_last_name"`
	BillingEmail         string              `json:"billing_email"`
	BillingAddress       sql.NullString      `json:"billing_address"`
	ShippingFirstName    string              `json:"shipping_first_name"`
	ShippingLastName     string              `json:"shipping_last_name"`
	ShippingEmail        string              `json:"shipping_email"`
	ShippingAddress      sql.NullString      `json:"shipping_address"`
	BillingPhone         sql.NullString      `json:"billing_phone"`
	ShippingPhone        sql.NullString      `json:"shipping_phone"`
	PaymentID            sql.NullString      `json:"payment_id"`
	TransactionSignature sql.NullString      `json:"transaction_signature"`
	DiscountAmount       sql.NullInt32       `json:"discount_amount"`
	DiscountCode         sql.NullString      `json:"discount_code"`
}

type OrderDetail struct {
	OdID          int32          `json:"od_id"`
	OrderID       sql.NullString `json:"order_id"`
	ProductID     sql.NullInt32  `json:"product_id"`
	ProductPrice  int32          `json:"product_price"`
	Quantity      int32          `json:"quantity"`
	DeliveryPrice int32          `json:"delivery_price"`
}

type Product struct {
	ProductID     int32          `json:"product_id"`
	CategoryID    sql.NullInt32  `json:"category_id"`
	ProductName   string         `json:"product_name"`
	Price         sql.NullInt32  `json:"price"`
	DeliveryPrice sql.NullInt32  `json:"delivery_price"`
	Gender        NullEnumGender `json:"gender"`
	ProductDesc   sql.NullString `json:"product_desc"`
	Quantity      sql.NullInt32  `json:"quantity"`
	CountryID     sql.NullInt32  `json:"country_id"`
	CreatedOn     sql.NullTime   `json:"created_on"`
	UpdatedOn     sql.NullTime   `json:"updated_on"`
	UpdatedBy     sql.NullInt32  `json:"updated_by"`
	Status        NullEnumStatus `json:"status"`
}

type ProductImage struct {
	ImgID      int32          `json:"img_id"`
	ProductID  sql.NullInt32  `json:"product_id"`
	ImageUrl   string         `json:"image_url"`
	CreatedOn  sql.NullTime   `json:"created_on"`
	UpdatedOn  sql.NullTime   `json:"updated_on"`
	UpdatedBy  sql.NullInt32  `json:"updated_by"`
	Status     NullEnumStatus `json:"status"`
	IsFeatured sql.NullBool   `json:"is_featured"`
}

type User struct {
	UserID    int32          `json:"user_id"`
	FirstName string         `json:"first_name"`
	LastName  sql.NullString `json:"last_name"`
	Email     string         `json:"email"`
	Phone     sql.NullString `json:"phone"`
	Password  string         `json:"password"`
	CreatedOn sql.NullTime   `json:"created_on"`
	UpdatedOn sql.NullTime   `json:"updated_on"`
	Status    NullEnumStatus `json:"status"`
	Access    NullEnumAccess `json:"access"`
}

type VProduct struct {
	ProductID     int32          `json:"product_id"`
	ProductName   string         `json:"product_name"`
	ImageUrl      string         `json:"image_url"`
	Quantity      sql.NullInt32  `json:"quantity"`
	CreatedOn     sql.NullTime   `json:"created_on"`
	Price         sql.NullInt32  `json:"price"`
	DeliveryPrice sql.NullInt32  `json:"delivery_price"`
	ProductDesc   sql.NullString `json:"product_desc"`
	Gender        NullEnumGender `json:"gender"`
	CategoryID    int32          `json:"category_id"`
	CategoryName  string         `json:"category_name"`
	CountryID     int32          `json:"country_id"`
	CountryName   string         `json:"country_name"`
}
