// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package db

import (
	"context"
	"database/sql"
)

type Querier interface {
	ActivateImages(ctx context.Context, arg ActivateImagesParams) error
	CountUser(ctx context.Context, lower string) (int64, error)
	CreateCategory(ctx context.Context, arg CreateCategoryParams) error
	CreateProduct(ctx context.Context, arg CreateProductParams) (Product, error)
	CreateProductImage(ctx context.Context, arg CreateProductImageParams) error
	DeleteCategory(ctx context.Context, categoryID int32) error
	DeleteOneProduct(ctx context.Context, productID int32) error
	FindAdminUser(ctx context.Context, lower string) (FindAdminUserRow, error)
	ReadCategory(ctx context.Context) ([]Category, error)
	ReadCategoryByID(ctx context.Context, categoryID int32) (Category, error)
	ReadOneProduct(ctx context.Context, productID int32) (VProduct, error)
	ReadOrderById(ctx context.Context, orderID string) (ReadOrderByIdRow, error)
	ReadOrderCountDaywise(ctx context.Context) ([]ReadOrderCountDaywiseRow, error)
	ReadOrderCountMonthwise(ctx context.Context) ([]ReadOrderCountMonthwiseRow, error)
	ReadOrderItems(ctx context.Context, orderID sql.NullString) ([]ReadOrderItemsRow, error)
	ReadOrders(ctx context.Context) ([]ReadOrdersRow, error)
	ReadProductImages(ctx context.Context, productID sql.NullInt32) ([]ReadProductImagesRow, error)
	ReadProducts(ctx context.Context) ([]ReadProductsRow, error)
	ReadUser(ctx context.Context, userID int32) (User, error)
	ReadUserCountDaywise(ctx context.Context) ([]ReadUserCountDaywiseRow, error)
	ReadUserCountMonthwise(ctx context.Context) ([]ReadUserCountMonthwiseRow, error)
	ReduceQuantity(ctx context.Context, arg ReduceQuantityParams) error
	RemoveFeaturedProductImage(ctx context.Context, productID sql.NullInt32) error
	RemoveImages(ctx context.Context, productID sql.NullInt32) error
	UpdateCategoryById(ctx context.Context, arg UpdateCategoryByIdParams) error
	UpdateOneProduct(ctx context.Context, arg UpdateOneProductParams) error
	UpdateOrderStatus(ctx context.Context, arg UpdateOrderStatusParams) (Order, error)
	UpdateProduct(ctx context.Context, arg UpdateProductParams) error
}

var _ Querier = (*Queries)(nil)
