// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package db

import (
	"context"
)

type Querier interface {
	CountUser(ctx context.Context, lower string) (int64, error)
	DeleteOneProduct(ctx context.Context) error
	FindAdminUser(ctx context.Context, lower string) (FindAdminUserRow, error)
	ReadOneProduct(ctx context.Context, productID int32) (ReadOneProductRow, error)
	ReadProducts(ctx context.Context, arg ReadProductsParams) ([]ReadProductsRow, error)
	ReadUser(ctx context.Context, userID int32) (User, error)
	UpdateOneProduct(ctx context.Context, arg UpdateOneProductParams) error
}

var _ Querier = (*Queries)(nil)
